# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 286106eeb79fc28681570467590bf44ccad0117b69737496a761e8c53c4fccc3d1a76ea9d8c41630b8f626e8872238d3685cfb4a691c4d35002546ebeebf94a4

test:
  secret_key_base: 0a367bfc33d5e22f8957ac277590adabbe8c0db6a3131a3a6f62d9a9e3a02342db95a358e703781d28e809e045a31e7f35d4bd528b66e9cb5a63c38d88788cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
